export {
  ALLOWED_CARTOON_ORDER_PHOTO_MIME_TYPES,
  ALLOWED_IMAGE_UPLOAD_MIME_TYPES,
  ALLOWED_VIDEO_MIME_TYPES,
  CARTOON_ORDER_PHOTO_PREFIX,
  MAX_CARTOON_ORDER_PHOTO_SIZE_BYTES,
  MAX_CARTOON_ORDER_PHOTOS,
  MAX_IMAGE_UPLOAD_SIZE_BYTES,
  MAX_VIDEO_DURATION_SECONDS,
  MAX_VIDEO_UPLOAD_SIZE_BYTES,
  MAX_VIDEOS_PER_PRODUCT,
  RECOMMENDED_VIDEO_DURATION_SECONDS,
} from '../../shared/config/productLimits.js';
